/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRideRouteImport } from './routes/test-ride'
import { Route as ScootersRouteImport } from './routes/scooters'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BikesRouteImport } from './routes/bikes'
import { Route as IndexRouteImport } from './routes/index'

const TestRideRoute = TestRideRouteImport.update({
  id: '/test-ride',
  path: '/test-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ScootersRoute = ScootersRouteImport.update({
  id: '/scooters',
  path: '/scooters',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesRoute = BikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bikes': typeof BikesRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/scooters': typeof ScootersRoute
  '/test-ride': typeof TestRideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bikes': typeof BikesRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/scooters': typeof ScootersRoute
  '/test-ride': typeof TestRideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bikes': typeof BikesRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/scooters': typeof ScootersRoute
  '/test-ride': typeof TestRideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bikes' | '/contact' | '/emi' | '/scooters' | '/test-ride'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bikes' | '/contact' | '/emi' | '/scooters' | '/test-ride'
  id:
    | '__root__'
    | '/'
    | '/bikes'
    | '/contact'
    | '/emi'
    | '/scooters'
    | '/test-ride'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BikesRoute: typeof BikesRoute
  ContactRoute: typeof ContactRoute
  EmiRoute: typeof EmiRoute
  ScootersRoute: typeof ScootersRoute
  TestRideRoute: typeof TestRideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-ride': {
      id: '/test-ride'
      path: '/test-ride'
      fullPath: '/test-ride'
      preLoaderRoute: typeof TestRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scooters': {
      id: '/scooters'
      path: '/scooters'
      fullPath: '/scooters'
      preLoaderRoute: typeof ScootersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes': {
      id: '/bikes'
      path: '/bikes'
      fullPath: '/bikes'
      preLoaderRoute: typeof BikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BikesRoute: BikesRoute,
  ContactRoute: ContactRoute,
  EmiRoute: EmiRoute,
  ScootersRoute: ScootersRoute,
  TestRideRoute: TestRideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
